name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - swiftlang/swift:nightly-main-focal
    container:
      image: ${{ matrix.images }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test
      run: swift test --enable-code-coverage
    # - name: Convert coverage files
    #   run: llvm-cov export -format="lcov" .build/debug/swift-extras-jsonPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov
    # - name: Install curl
    #   run: apt-get update && apt-get install -y curl # required by the codecov action.
    # - name: Upload to codecov.io
    #   uses: codecov/codecov-action@v1
    #   with:
    #     file: info.lcov

  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}